# Generated by Django 4.2 on 2023-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photopost", old_name="User", new_name="user",
        ),
        migrations.AddField(
            model_name="photopost",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="videos", verbose_name="動画"
            ),
        ),
    ]
