# Generated by Django 4.2 on 2023-06-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0005_photopost_created_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="photopost", name="created_at",),
    ]
